name: Update Schachtabelle

on:
  schedule:
    - cron: '0 6 * * *'  # Jeden Tag um 6 Uhr UTC
  workflow_dispatch:      # Manuell auslösbar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: pip install requests beautifulsoup4

      - name: Tabelle generieren
        run: python update_table.py

      - name: Geänderte Datei pushen
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Stelle sicher, dass dein Secret so heißt!
        run: |
          echo "✅ Token-Test: Länge = ${#GH_TOKEN}"
          git config --global user.name "FPantleon"
          git config --global user.email "florian.pantleon@outlook.de"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add index.html || true
          git commit -m "Automatisch aktualisiert: Tabelle" || echo "Nichts zu committen"
          git push origin main || echo "❌ Push fehlgeschlagen"

