name: Update Schachtabelle 2. Mannschaft

on:
  schedule:
    - cron: '20 6 * * *'  # Täglich um 06:20 UTC (07:20 deutsche Zeit)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: pip install requests beautifulsoup4

      - name: Tabelle generieren
        run: python update_table_2.py

      - name: Geänderte Datei pushen
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "✅ Token-Test: Länge = ${#GH_TOKEN}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bettringen2.html || true
          git commit -m "Automatisch aktualisiert: Tabelle 2. Mannschaft" || echo "Nichts zu committen"
          git push origin main || echo "❌ Push fehlgeschlagen"

