name: Update Mannschaftsaufstellung

on:
  schedule:
    - cron: '15 6 * * *'  # Täglich um 06:15 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: pip install requests beautifulsoup4

      - name: Aufstellung generieren
        run: python update_aufstellung.py

      - name: Geänderte Datei pushen
        run: |
          echo "✅ Token-Test: Länge = ${#GH_TOKEN}"
          git config --global user.name "FPantleon"
          git config --global user.email "florian.pantleon@outlook.de"
          git add aufstellung.html || true
          git commit -m "Automatisch aktualisiert: Mannschaftsaufstellung" || echo "Nichts zu committen"
          git push origin main || echo "❌ Push fehlgeschlagen"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
