name: Update Schachtabelle

on:
  schedule:
    - cron: '0 6 * * *' # Jeden Tag um 6 Uhr morgens (UTC)
  workflow_dispatch: # Manuell auslösbar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: pip install requests beautifulsoup4

      - name: Tabelle generieren
        run: python update_table.py

      - name: Geänderte Datei pushen
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html
          git commit -m "Automatisch aktualisiert: Tabelle"
          git push
